- name: Sysctl Kubernetes Tweaks 
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
  loop: "{{ sysctl_params }}"