- name: Creates Kubectl Directory
  file:
    path: "~/.kube"
    state: directory
  become_user: "{{ k8s_admin_user }}"
- name: Copy Kubectl Config
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "~/.kube/config"
    owner: "{{ k8s_admin_user }}"
    group: "{{ k8s_admin_user }}"
