- name: Creates Kubectl Directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
- name: Copy Kubectl Config
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
