- name: Creates Kubectl Directory
  file:
    path: "/home/{{ k8s_admin_user }}/.kube"
    state: directory

- name: Copy Kubectl Config
  copy:
    remote_src: yes
    src: "{{ k8s_admin_conf }}"
    dest: "/home/{{ k8s_admin_user }}/.kube/config"
    owner: "{{ k8s_admin_user }}"
    group: "{{ k8s_admin_group }}"
