- name: "Create {{ k8s_admin_group }} Group"
  group:
    name: "{{ k8s_admin_group }}"
    state: present

- name: "Allow {{ k8s_admin_group }} Group to Have Passwordless sudo"
  lineinfile:
    dest: "{{ sudoers_file }}"
    state: present
    regexp: "^%{{ k8s_admin_group }}"
    line: "%{{ k8s_admin_group }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'

- name: "Add {{ k8s_admin_user }} User to {{ k8s_admin_group }} Group"
  user:
    name: "{{ k8s_admin_user }}"
    groups: "{{ k8s_admin_group }}"
    append: yes
    state: present
    create_home: yes

- name: "Set up Authorized Keys for the {{ k8s_admin_user }} User"
  authorized_key:
    user: "{{ k8s_admin_user }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"

- name: Become K8S Admin User
  command: whoami
  become: yes
  become_user: "{{ k8s_admin_user }}"
