---
- hosts: all
  tasks:
    - name: Label Worker Nodes
      command: "kubectl label node {{ item }} node-role.kubernetes.io/worker=worker"
      loop:
        - k8s-worker-0
        - k8s-worker-1
