Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.define "k8s-master" do |master|
    master.vm.provider :digital_ocean do |provider, override|
      override.ssh.private_key_path = '~/.ssh/id_rsa'
      override.vm.box = 'digital_ocean'
      override.vm.box_url = 'https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box'
      override.nfs.functional = false
      provider.token = "#{ENV['DO_API_KEY']}"
      provider.ssh_key_name = 'bugron'
      provider.image = 'centos-7-x64'
      provider.region = 'fra1'
      provider.size =  's-2vcpu-2gb'
      provider.private_networking = true
    end
    master.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'k8s-setup/master-playbook.yml'
    end
    master.vm.synced_folder ".", "/vagrant", type: "rsync"
		master.vm.hostname = 'k8s-master'
  end
end
